hellomake: level9.cpp pair.cpp
	g++ -o task9 level9.cpp pair.cpp

# files on the 'title' line are prerequisites. They must exist before the script is run.

# '-c' : make an object file, not an executable. Object files don't need 'main()', executables DO
